settings:
    notify_email_address: pic@example.com
    sample_interval: 10
    light_start_time: '10:00'
    light_end_time: '15:00'
    light_schedule_enabled: false
    show_charts: true
    channels:
        1:
            number: 1
            sensor_class_name: Caece\PicBundle\PicSensor\Sensor\Concrete\SolarRadiationSensor
            active: true
            begin_threshold: 100
            end_threshold: 900
        2:
            number: 2
            sensor_class_name: Caece\PicBundle\PicSensor\Sensor\Concrete\TemperatureSensor
            active: true
            begin_threshold: 100
            end_threshold: 900
        3:
            number: 3
            sensor_class_name: Caece\PicBundle\PicSensor\Sensor\Concrete\WindSpeedSensor
            active: true
            begin_threshold: 100
            end_threshold: 900
        4:
            number: 4
            sensor_class_name: Caece\PicBundle\PicSensor\Sensor\Concrete\SolarCellStatus
            active: true
        5:
            number: 5
            sensor_class_name: Caece\PicBundle\PicSensor\Sensor\Concrete\CabinetStatus
            active: true